### PR TITLE
add __lark_meta__ dunder

### LINKED ISSUE #9: Meta is always empty while using cython lark
This is my parser:

```python3
    lark_kwargs = {
        "parser": "lalr",
        "lexer": "contextual",
        "propagate_positions": True,
        "_plugins": lark_cython.plugins,
    }
    lang_parser = Lark(lang_def, start="start", **lark_kwargs)
```
I'd like to propagate the line positions, without cython-lark it works fine, but once i enable the plugins the meta value is always empty.

Do you have any suggestion on what's wrong ?

### PR DESCRIPTION
**Pull request by ernestoarbitrio**
TBH I don't know how to test it better and write more meaningful test. 
Any suggestion is more than welcome

FIXES #9

### CODE REVIEW

**Comment by erezsh** [comment]
It's a good start, but make sure the meta attributes are filled in correctly. `line`, `column`, `end_line`, etc.

**Comment by erezsh** [comment]
Thanks.

Sorry I forgot to mention, can you also make sure to test it with a Tree instance? (you can just add a rule to the grammar, and check its meta has attributes too)

**Comment by erezsh** [comment]
It's odd that the tests are passing.. how can that be if I didn't merge the Lark PR yet?

**Comment by ernestoarbitrio** [comment]
> It's odd that the tests are passing.. how can that be if I didn't merge the Lark PR yet?

I think this is not odd since I did not send the meta through the Tree. The token has the `line` etc... but the Tree still has meta empty. So I wonder how can I exercise a test for this scenario

**Comment by ernestoarbitrio** [comment]
> It's odd that the tests are passing.. how can that be if I didn't merge the Lark PR yet?

maybe i got it ... writing a test

**Comment by ernestoarbitrio** [comment]
ok now it should fail. FYI on my machine it passes cause I have the `parse_tree` edited as you PR in `lark`

**Comment by erezsh** [comment]
Looks good! I'll merge it after next Lark release.

**Comment by erezsh** [comment]
@ernestoarbitrio The tests are still failling after releasing 1.1.4, any idea why?

**Comment by ernestoarbitrio** [comment]
> @ernestoarbitrio The tests are still failling after releasing 1.1.4, any idea why?

looking into it

**Comment by ernestoarbitrio** [comment]
Now it should work

**Pull request merged**
